RUN_DEV_MODE = False

# Config files
BATCH_CONFIG_PREFIX = "."
ONLINE_CONFIG_PREFIX = None
MAIN_ONLINE_CONFIG_DIR = "/var/task"
MAIN_CONFIG_DIR = "."

LOGGER_CONFIG = "logger.yml"
KAFKA_CONFIG = "kafka.yml"
DB_CONFIG =  "database.yml"
APP_CONFIG =  "application.yml"
JOB_CONFIG = "job.yml"
MODEL_CONFIG = "model.yml"
DATA_CONFIG = "data.yml"
TASK_CONFIG = "task.yml"
API_USECASE_CONFIG =  "usecases.yml"
SMMME_CONFIG = "sagemaker_mme.yml"
LLM_CONFIG = "platform_llm.yml"
DELTA_SHIPER_CONFIG = MAIN_ONLINE_CONFIG_DIR + "delta_shipper_config.properties"

CONFIG_OPSWORKS, CONFIG_LOCAL = "opsworks", "local"


# Logger realted
LOG_CONSUMER = "consumer"
LOGGER_NAME = "logger_name"
LEVELNAME = "levelname"
CRITICAL = "CRITICAL"
ERROR = "ERROR"
INFO = "INFO"

# Databricks / Delta related
DATABRICKS_DB_NAME = "freddy_fm_d2c"

# Job
JOB_PARENT_PREFIX = "train_job_"
PRODUCTION = "production"
STAGING = "staging"
TRAIN = "train"

# Columns in the data
MCR_CONTACT_ID = "mcr_contact_id"
CONTACT = "contact"
ACCOUNT_ID = "account_id"
NAME = "name"
EVENT_TIMESTAMP = "event_timestamp"
EVENT_PROPERTIES = "event_data"
COUNTRY = "country"
PRODUCT_ID = "product_id"
PRODUCT_IDS = "product_ids"
ITEM_ID = "item_id"
CATEGORY_ID = "category_id"
MCR_ACCOUNT_ID = "mcr_account_id"
QUANTITY = "quantity"
MCR_ACCOUNT_ID_USER = "mcr_account_id_user"
MCR_ACCOUNT_ID_ITEM = "mcr_account_id_item"
ORDER_ID = "order_id"
ITEM_CNT = "item_cnt"
TITLE = "title"
EVENT_DATE = "event_date"
EVENT_AT = "event_at"
DATA_CONFIG_KEY = "data_config"
MODEL_CONFIG_KEY = "model_config"
DATE_CONFIG_KEY = "date_cofig"
DELTA = "delta"
USER = "user"
EMBEDS = "embeds"
EMBEDS1 = "embeds1"
USER_EMBED = "user_embed"
ITEM_EMBED = "item_embed"
ITEM = "item"
ITEM1 = "item1"
ITEMS = "items"
SCORE = "score"
PAIRS = "pairs"
NON_ITEMS = "non_items"
LINK_EMBEDDING = "link_embedding"
LINK = "link"
FEATURE = "feature"
PRODUCT = "product"
SCORE = "score"
CATALOGUE_SIZE = "catalogue_size"
CUSTOMER_BASE_SIZE = "customer_base_size"
TRANSACTION_COUNT = "transaction_count"
PRODUCTS_BY_TRANSACTION = "products_by_transaction"
TOTAL_TRANSACTIONS = "total_transactions"
PURCHASE_COUNTS = "purchase_counts"
NORMALIZED_PURCHASE_COUNTS = "normalized_purchase_counts"
GROUPED_EVENTS = "grouped_events"
TOTAL_PURCHASES = "total_purchases"
RECOM = "recommendations"
PRODUCT_A = "Product_A"
PRODUCT_B = "Product_B"
GLOBAL = "global"
NUM_PRODUCTS = "num_products"
NUM_TRANSACTIONS = "num_transaction"


# Task

RUN_ID = "run_id"
USER_PREFERENCE = "user_preference"
NEW_TRANSACTION = "new_transaction"
ITEM_EMBEDDING = "item_embedding"
EMBEDDING = "embedding"
USER_EMBEDDING = "user_embedding"
FREQUENTLY_PURCHASED_TOGETHER = "frequently_purchased_together"
CONTACT_EMBEDDING = "contact_embedding"
ITEM_SIMILARITY = "item_similarity"
ACCOUNT_PREFERENCE = "account_preference"
IS_AGGREGATE = "is_aggregate"
U2I = "u2i"
I2I = "i2i"
MODELS = "models"
LINK = "link"
PRODUCTION = "production"
RANK = "rank"
TYPE = "type"
RECOM_LIST_ID = "recommendation_list_id"
RECOM_LIST_SCORE = "recommendation_list_score"
TF_HUB_URL = "https://tfhub.dev/google/universal-sentence-encoder/4"
STATUS = "status"
MESSAGE = "message"

# Model related column names
MODEL_TYPE = "model_type"
MODEL_GRAPH = "graph"
MODEL_GRAPH_DGL = "graph_dgl"
MODEL_RERANKER = "reranker"
MODEL_CONTENT = "content"
MODEL_GRAPH_I2I = "graph_i2i1"
GRAPH_FPT = "graph_fpt"
MODEL_GRAPH_DGL_I2I = "graph_dgl_i2i"
MODEL_MF_BPR = "mf_bpr"
MODEL_FPT = "fpt"
USE_EMBED = 'use_embed'
FPGROWTH = "fpgrowth"
MODEL_AGG_POPULAR_PRODUCTS = "agg_popular_products"
MODEL_AGG_TRENDING_PRODUCTS_ZSCORE = "agg_trending_products_zscore"
MODEL_AGG_TRENDING_PRODUCTS_MODIFIED_ZSCORE = "agg_trending_products_modified_zscore"
GRAPH_U2I = "graph_u2i"
TFIDF_I2I = "tfidf_i2i"
FPT_I2I = "fpt_i2i"
USER_ID = "user_id"
ITEM_ID = "item_id"
ENGMT_SCORE = "engmt_score"
EVENT_SCORE = "event_score"
EVENT_TYPE = "event_type"
VIEWED = "VIEWED"
PURCHASED = "PURCHASED"
ONE = 1.0
TWO = 2.0
SUM = "sum"
ALS = "als"
BPR = "bpr"
LMF = "lmf"
COUNT = "count"
K = 10
U2U_RECOMMENDATIONS = "u2u_recommendations"
OVERWRITE = "overwrite"
APPEND = "append"
MERGE = "merge"
FACTORS = "factors"
REGULARIZATION = "regularization"
ACCOUNT_NAME = "account_name"
BEST_PARAMS = "best_params"
LEARNING_RATE = "learning_rate"
ITERATIONS = "iterations"
VERIFY_NEGATIVE_SAMPLES = "verify_negative_samples"
RECORDS = "records"
IS_AGGREGATE = "is_aggregate"

# Reranker Related
RERANKER_TOP_K = 3
PRODUCT_TITLE = "product_title"
PRODUCT_PRICE = "price"
PRODUCT_VENDOR = "product_vendor"
PRODUCT_ID = "product_id"
MODEL = "fullslate_q-og"
BASE_PATH = "/dbfs/tmp/models"
DUMP_PATH = "/dbfs/tmp/abhishek/rl"
MODEL_PATH = f"{BASE_PATH}/{MODEL}"
CANDIDATE_SIZE = 10
EMBEDDING_PATH = "/dbfs/tmp/data"
GRAPH_PATH = "/dbfs/FileStore/graph_embed.csv"
SLATE_SIZE = 3
ACCOUNT_PATHS = "/dbfs/tmp/abhishek"
TEST_CHECKPOINT = "test/checkpoints"
CUSTOMER_EMBEDDING = "customer-embedding"
CUSTOMER_IDS = "customer-ids"
PRODUCT_EMBEDDING = "product-embedding"
WEEKDAY = "weekday"
DATE = "date"

# Content Based
CONTENT_TOP_K = 10

A2I = "a2i"
AVG_PROD_PRUCHASE_COUNT = "product_avg_purchase_count"
ABS_DEV = "abs_dev"
ARRAY_OF_STRUCT = "array_of_struct"
NUM_RECOMM = "num_recomm"
BASKET_SIZE = "basket_size"
PERIOD = "period"

# AWS S3 related
VERSION = 1
BASE_DIRECTORY = ""
REGION_BUCKET_IND = "freddy-freshsales-prod-ind"
REGION_BUCKET_US = "freddy-freshsales-prod"
REGION_BASE_DIRECTORY_US = "abhishek"
REGION_BASE_DIRECTORY_IND = "abhishek"

# popular and trending products
PURCHASE_COUNT = "purchase_count"
MAX = "max"
ACCOUNT_LATEST_DATE = "account_latest_date"
INNER = "inner"
AGE = "AGE"
MEDIAN_PURCHASE_COUNT = "product_level_median_purchase_count"
ROW_NUMBER = "row_number"
POPULAR_PRODUCTS = "popular_products"
ACCOUNT_OLDEST_DATE = "account_oldest_date"
SEQUENCE = "sequence"
DATES = "dates"
LEFT_OUTER = "left_outer"
AVG = "avg"
STDDEV = "stddev"
Z_SCORE = "z_score"
TRENDING_PRODUCTS = "trending_products"
ACCT_AVG_PURCHASE_COUNT = "acct_avg_purchase_count"
MEAN = "mean"
MEDIAN = "median"
MEAN_AD = "meanAD"
MEDIAN_AD = "medianAD"
MODIFIED_Z_SCORE = "modified_z_score"
TOTAL_OBSERVATIONS = "total_observations"

# MF_BPR_MODEL CONSTANTS
ENGAGEMENT_SCORE = "engagement_score"
VALID_PRECISION_AT = "valid_precision@"
VALID_MAP_AT = "valid_map@"
VALID_NDCG_AT = "valid_ndcg@"
VALID_AUC_AT = "valid_auc@"
PRECISION = "precision"
MAP = "map"
NDCG = "ndcg"
AUC = "auc"
FSA_ACCOUNT_ID = "fsa_account_id"

MF_BPR_ARTIFACTS_DIR = "/dbfs/tmp/sanjeev/{}_mf_bpr_artifacts"
MF_BPR_MODEL_NAME = "mf_bpr_model.pkl"
MF_BPR_I2C_MAP_NAME = "index_to_customer_map.pkl"
MF_BPR_I2P_MAP_NAME = "index_to_product_map.pkl"
MF_BPR_INT_MAT_NAME = "interaction_matrix.pkl"

MODEL_PATH = "model_path"
I2C_MAP_PATH = "i2c_map_path"
I2P_MAP_PATH = "i2p_map_path"
INT_MAT_PATH = "interaction_matrix_path"
MODEL = "model"
START_DATE = "start_date"
END_DATE = "end_date"
TEST_PERIOD_IN_DAYS = "test_period_in_days"
TRAIN_PERIOD_IN_DAYS = "train_period_in_days"

# FPGrowth model constants

ANTECEDENT = "antecedents"
CONSEQUENT = "consequents"
LIFT = "lift"
SUPPORT = "support"
CONFIDENCE = "confidence"
SIMILARITY_SCORE = "similarity_score"
ASSOCIATION_RULES_PATH = "association_rules_path"
ITEM_ITEM_PATH = "item_item_path"
FPGRWOTH_MODEL_ARTIFACTS_DIR = "/dbfs/tmp/shivam/{}_fpgrowth_artifacts"
FPGROWTH_MODEL_NAME = "fpt_fpgrowth.pkl"
FPGROWTH_ASSC_RULE_NAME = "association_rules.pkl"
FPGROWTH_ITEM_ITEM_NAME = "item_item.pkl"

# Dynamodb tables related
TTL_TIME = "ttl_time"
PARTITION_KEY = "partition_key"
INGESTED_AT = "ingested_at"
_ATTRIBUTES = "_attributes"
D2C_RECOMMENDATION_TABLE_USER_ITEM = "d2c_recommendation_table_user_item"
D2C_RECOMMENDATION_TABLE_ITEM_ITEM = "d2c_recommendation_table_item_item"
D2C_RECOMMENDATION_TABLE_ACCOUNT_LEVEL_ITEM = (
    "d2c_recommendation_table_account_level_item"
)
D2C_RECOMMENDATION_TABLE_NEXT_PURCHASE = "d2c_recommendation_next_purchase"
D2C_FILTER_TABLE_RECENT_PURCHASE = "d2c_filter_table_recent_purchase"
D2C_PRODUCT_VARIANT_TABLE = "d2c_product_variant_mapping"
D2C_RFM_SEGMENT_MAP_TABLE = "d2c_rfm_segment_fm_mapping"

# AWS related
AWS_REGION = "AWS_REGION"
REGION_US = "us-east-1"
REGION_AUS = "ap-southeast-2"
REGION_EU = "eu-central-1"
REGION_IND = "ap-south-1"
STS = "sts"
AWS_ARN_DATABRICKS_DYNAMODB_PROD = (
    "arn:aws:iam::594542760018:role/databricks-dynamo-db-sto-access-role"
)
AWS_ARN_DATABRICKS_DYNAMODB_STAGING = (
    "arn:aws:iam::372575104561:role/databricks_staging_dynamo_access_role"
)

AWS_ARN_SAGEMAKER_PROD = "arn:aws:iam::594542760018:role/deal_forecasting_role"
AWS_ARN_SAGEMAKER_STAGING = "arn:aws:iam::372575104561:role/freddy_deals_forecasting_role"

ASSUME_ROLE_SESSION1 = "AssumeRoleSession1"
CREDENTIALS = "Credentials"
ACCESS_KEY_ID = "AccessKeyId"
SECRET_ACCESS_KEY = "SecretAccessKey"
SESSION_TOKEN = "SessionToken"
PAY_PER_REQUEST = "PAY_PER_REQUEST"
DYNAMODB_WRITE_BATCH_SIZE = 500

# AWS SAGAMAKER END POINT
SAGEMAKER = "sagemaker"
CONTAINER_URL_PREFIX = "{}.dkr.ecr.{}.amazonaws.com/{}:latest"
ACCOUNT_STRING = "Account"
SM_MME_DATE_FORMAT = "%Y-%m-%d-%H-%M-%S"
MODEL_S3_URL_PREFIX = "s3://{}/{}/"
CONTAINER_IMAGE = "Image"
MODEL_DATA_URL = "ModelDataUrl"
CONTAINER_MODE = "Mode"
INSTANCE_TYPE = "InstanceType"
INITIAL_INSTANCE_COUNT = "InitialInstanceCount"
INITIAL_VARIANT_WEIGHT = "InitialVariantWeight"
MODEL_NAME_SAGEMAKER = "ModelName"
VARIANT_NAME = "VariantName"
SLATEQ_MODEL_NAME = "pr-reranker-slateq"
SLATEQ_END_POINT_NAME_PREFIX = SLATEQ_MODEL_NAME + "-end-point"
SLATEQ_END_POINT_CONFIG_NAME_PREFIX = SLATEQ_MODEL_NAME + "-config-"
SLATEQ_MODEL_NAME_PREFIX = SLATEQ_MODEL_NAME + "-model"
ENDPOINT_STATUS = "EndpointStatus"
ENDPOINT_URL = "https://7ixjd0kxn7.execute-api.ap-south-1.amazonaws.com/prod/freddy-api/product-recommendation/devops/sagemaker/deploy_endpoint"
S3_BUCKET = "s3_bucket"
ARTIFACT_PATH = "artifact_path"

# StageLogger class related
STAGE_INFO_RETRIEVAL_STAGE = "Stage_info_Retrieval_stage"
STAGE_INFO_FILTER_STAGE = "Stage_info_Filter_stage"
STAGE_INFO_BACKFILL_STAGE = "Stage_info_Backfill_stage"
STAGE_INFO_RANKING_STAGE = "Stage_info_Ranking_stage"
MODEL_LIST = "model_list"
FILTER_LIST = "filter_list"
BACKFILL_LOGIC = "backfill_logic"
CANDIDATES = "candidates"
RECOMMENDATION_TYPE = "recommendation_type"
ENDPOINT_POINT_CONFIG_NAME = "endpoint_point_config_name"
MODEL_NAME = "model_name"
RANKER_NAME = "ranker_name"
SAGEMAKER_CONFIG_NAME = "sagemaker_config_name"
SAGEMAKER_MODEL_NAME = "sagemaker_model_name"

# TimeLogger class related
TIME_TAKEN_RETRIEVAL_STAGE = "Time_taken_Retrieval_Stage"
TIME_TAKEN_FILTER_STAGE = "Time_taken_Filter_Stage"
TIME_TAKEN_RANKER_STAGE = "Time_taken_Ranker_Stage"
TIME_TAKEN_BACKFILL_STAGE = "Time_taken_Backfill_Stage"
TIME_TAKEN_VARIANT_MAPPER_STAGE = "Time_taken_Variant_Mapping_Stage"
TIME_TAKEN_FETCH_DYNAMODB_MODEL_U2I = "Time_taken_fetch_DynamoDB_model_u2i"
TIME_TAKEN_FREDDY_SHIPPER_REGISTER = "Time_taken_Freddy_Shipper_Register"
TIME_TAKEN_FREDDY_SHIPPER_KAFKA_PUSH = "Time_taken_Freddy_Shipper_kafka_push"
TIME_TAKEN_LOAD_SLATEQ_MODEL = "Time_taken_load_SlateQ_model"
TIME_TAKEN_PREPROCESS_SLATEQ_MODEL = "Time_taken_preprocess_SlateQ_model"
TIME_TAKEN_POSTPROCESS_SLATEQ_MODEL = "Time_taken_postprocess_SlateQ_model"
TIME_TAKEN_INFERENCE_SLATEQ_MODEL = "Time_taken_inference_SlateQ_model"

# serving module related
RESOURCE = "resource"
BODY = "body"
CAPS_BODY = "Body"
DATA = "data"
API_TYPE = "api_type"
USECASE = "usecase"
RECOMMENDATIONS = "recommendations"
NUM_RECOMMENDATIONS = "num_recommendations"
RECOMMENDATION_LIST_ID = "recommendation_list_id"
REC_ID = "rec_id"
RECOMMENDATION_ID = "recommendation_id"
RECOMM_LENGTH = "recomm_length"
PREDICTIONS = "predictions"
CONTEXT = "context"
DEBUG = "debug"
PERSIST_DELTA = "persist_delta"
USER_ITEM = "user-item"
LIST_MCR_CONTACT_ID = "list_mcr_contact_id"
INPUT = "input"
KEYS = "keys"
CANDIDATE_LIST = "candidate_list"
REQ_DATA = "req_data"
LIST_ITEM_ID = "list_item_id"
ACCOUNT = "account"
DEBUG_INFO = "debug_info"
STATUSCODE = "statusCode"
HEADERS = "headers"
CONTENT_TYPE = "Content-Type"
ACCEPT = "accept"
APPLICATION_JSON = "application/json"
ERROR_MSG = "error_msg"
TRACEBACK = "traceback"
HTTP_ERROR_200 = 200
HTTP_ERROR_500 = 500
ONLINE = "online"
OFFLINE = "offline"
USECASE_SMART_RECOMMENDATION = "smart_recommendation"
USECASE_SMART_RECOMMENDATION_AIF = "aif_category_products"
SAGEMAKER_RUNTIME = "sagemaker-runtime"
PAYLOAD = "payload"
API_PAYLOAD_VERSION = "1.0"
API_PAYLOAD_TYPE = "d2c_recomm"
PAYLOAD_TYPE = "payload_type"
PAYLOAD_VERSION = "payload_version"
REGION = "region"
INPUT_COUNTS = "input_counts"
RESULT_COUNTS = "result_counts"
FAILED_INPUTS = "failed_inputs"
LATENCY = "Latency"
BACKFILL_PRODUCTS = "backfill_products"
FILTER_TYPE_RECENT_PURCHASE = "filter_recent_purchase"
FILTER_TYPE_OUT_STOCK = "filter_out_stock"
GET = "GET"
POST = "POST"
HTTP_METHOD = "httpMethod"
SUCCESS = "Success"
PATH = "path"
API_BASE_URL = "/freddy-api/product-recommendation"
ROUTE_KEY = "routeKey"

# Freddy shipper related
FS_TENANT_NAME = "fsales-freddy"
FS_SVC_NAME = "fm_product_recommendation_test"
FS_VERSION = "v1.0"
FS_LOCALE = "en"
FS_BU_NAME = "Fsales"
FS_TEAM_NAME = "Freddy-Fsales"
FS_PRODUCT_NAME = "Freshmarketer"
FS_FEATURE_NAME = "product_recommendation"
FS_TAGS = None
FS_CHANNEL = ""
FS_PUSH_TO_DATABRICKS = True
FS_PUSH_TO_PROMETHEUS = False
FS_QUERY_ID = 1234
DEVELOPMENT = "development"
FS_FIELD1 = "field1"
FS_FIELD2 = "field2"
FS_FIELD3 = "field3"
FS_FIELD4 = "field4"

# Kafka consumer related
USER_NAME = "user_name"
PASSWORD = "password"
CONSUMER_GROUP_ID = "consumer_group_id"
OFFSET_RESET = "offset_reset"
INPUT_TOPICS = "input_topics"
TOPIC = "topic"
PARTITION = "partition"
OFFSET = "offset"


# Freshsales CPQ cache related
CPQ_URL = "xxxxxxxxxxxxxx"
CPQ_CACHE_ACCOUNTS_MAX_LIMIT = 50
CPQ_CACHE_ITEMS_MAX_SIZE = 250
CPQ_CACHE_ACCOUNTS_TTL = 12
CPQ_CACHE_ITEMS_TTL = 1
DELAY = "delay"
INVENTORY = "inventory"
AVAILABLE_COUNT = "available_count"
TOTAL_COUNT_BEFORE_FILTER = "total_count_before_filter"
TOTAL_COUNT_AFTER_RECENT_PURCHASE_FILTER = "total_count_after_recent_purchase_filter"
TOTAL_COUNT_AFTER_OUT_STOCK_FILTER = "total_count_after_out_stock_filter"


# llm related 
TENANT = "freshmarketer"
PLATFORM_GPT_URL = "http://freddy-ai-platform-stage.freshedge.net"
